language: go
go:
- 1.13

jobs:
  include:
    - stage: style
      script:
        - ./.travis.gofmt.sh
        - ./.travis.govet.sh
        - ./.travis.golint.sh
        - ./.travis.gocyclo.sh
    - stage: unit tests
      before_script: go build
      script:
        - go test -coverprofile coverage.out $(go list ./... | grep -v tests)
        - go tool cover -func=coverage.out
    - stage: REST API tests
      script:
        - ./test.sh

stages:
  - style
  - unit tests
  - REST API tests
